Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
Traceback (most recent call last):
  File "/home/zzli/anaconda3/envs/funcx-test/bin/process_worker_pool.py", line 4, in <module>
    __import__('pkg_resources').run_script('parsl==0.7.2', 'process_worker_pool.py')
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 566, in <module>
    manager.start()
  File "/gpfs/mira-home/zzli/anaconda3/envs/funcx-test/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/EGG-INFO/scripts/process_worker_pool.py", line 438, in start
    self.procs[proc_id].is_alive()))                
AttributeError: 'Popen' object has no attribute 'is_alive'
aprun: Apid 12865775: Caught signal Terminated, sending to application
